### ISSUE TITLE
zsh: command not found: wine

### ISSUE THREAD

**Issue by Mikeblackbelt** [BrandonXLF/exe-runner#1]
error above

**Comment by BrandonXLF** [comment]
On Linux and Mac, wine must be installed to run exe files, do you have wine?

**Comment by Mikeblackbelt** [comment]
No, Thanks for letting me know. I am not sure where to download it however.

**Comment by Mikeblackbelt** [comment]
Could you send me a link?

**Comment by BrandonXLF** [comment]
You should be able to find something here [https://wiki.winehq.org/Download](https://wiki.winehq.org/Download)

**Comment by Mikeblackbelt** [comment]
Thanks!
