### ISSUE TITLE
Add option to run the .exe file with $PWD set to the folder that containing the .exe file

### ISSUE THREAD

**Issue by ukyouz** [BrandonXLF/exe-runner#2]
Some .exe file expects external resource files with relative path that referring to the .exe file folder, rather than project folder root (ie. git root). 

I hope there will be a such feature implanted in this plugin.

**Comment by BrandonXLF** [comment]
I have addressed this in version v1.0.0, which will be published shortly. Jsut enable the setting `exeRunner.runInFileDirectory`. Please let me know if you have any more problems or suggestions.
