### ISSUE TITLE
Unable to Run .NET Core Executable Files on Windows Using Exe Runner

### ISSUE THREAD

**Issue by mjalav** [BrandonXLF/exe-runner#4]
When attempting to run executable files generated from .NET Core applications in Windows using the GitHub Repository Exe Runner, users encounter an error indicating that the command is not recognized. The error message suggests using the correct path by prefixing the executable with .\\
Error Message:

> a.exe : The term 'a.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
>+ a.exe
>+ ~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : ObjectNotFound: (a.exe:String) [], CommandNotFoundException
>    + FullyQualifiedErrorId : CommandNotFoundException
>
>Suggestion [3,General]: The command a.exe was not found, but does exist in the current location. Windows PowerShell does not load >commands from the current location by default. If you trust this command, instead type: ".\a.exe". See "get-help >about_Command_Precedence" for more details.

By following these steps, users will be able to execute the .NET Core executable file successfully on Windows without encountering the "command not found" error.
1- Open PowerShell or the command prompt.
2- Navigate to the directory containing the executable file using the cd command. For example:
`cd C:\path\to\directory`
3- Run the executable file by prefixing it with .\\ For example:
`.\a.exe`

**Comment by BrandonXLF** [comment]
Although it doesn't exactly match the error you are getting, I released [version 1.1.1](https://github.com/BrandonXLF/exe-runner/releases/tag/v1.1.1) that addresses another issue when running exes through PowerShell. Can you try it and let me know if it resolves your issue?

**Comment by mjalav** [comment]
Thanks @BrandonXLF ,  Yes , the issue resolved.
