### ISSUE TITLE
Currently broken on new update

### ISSUE THREAD

**Issue by KingKDot** [BrandonXLF/exe-runner#5]
exe runner no longer works on any windows exe I have tried ever since the new update (nim binaries, bun binaries, etc).

**Comment by BrandonXLF** [comment]
I just released [version 1.1.1](https://github.com/BrandonXLF/exe-runner/releases/tag/v1.1.1) that allows exes to run properly PowerShell. Please give it a try to see if it resolves your issue.

If the update doesn't work, can you tell me what error you are seeing, what operating system you're using, and what your default terminal profile is?

**Comment by KingKDot** [comment]
> I just released [version 1.1.1](https://github.com/BrandonXLF/exe-runner/releases/tag/v1.1.1) that allows exes to run properly PowerShell. Please give it a try to see if it resolves your issue.
> 
> If the update doesn't work, can you tell me what error you are seeing, what operating system you're using, and what your default terminal profile is?

works now thank you 👍
